# The following line is only required for old installations
# version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  sqldb:
      image: mysql:8.3
      volumes:
          - mysql_data:/var/lib/mysql
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      command: --default-storage-engine innodb
      restart: unless-stopped
      ports:
          - 3308:3306
      healthcheck:
          test: mysqladmin -p${MYSQL_ROOT_PASSWORD} ping -h localhost
          interval: 20s
          start_period: 10s
          timeout: 10s
          retries: 3

  kimai:
      build: .
      image: custom-kimai:latest
      volumes:
          - kimai_data:/opt/kimai/var/data
          - ${DATA_FOLDER}/kimai_config/local.yaml:/opt/kimai/config/packages/local.yaml
          - ${DATA_FOLDER}/invoices:/opt/kimai/var/invoices
          - ${DATA_FOLDER}/plugins:/opt/kimai/var/plugins
      ports:
          - 8888:8001
      environment:
          - ADMINMAIL=${KIMAI_USER}
          - ADMINPASS=${KIMAI_PASSWORD}
          - "DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}?charset=utf8mb4&serverVersion=8.3.0"
          - TRUSTED_HOSTS=localhost|127.0.0.1|${SUBDOMAIN}.${DOMAIN_NAME}
          - TZ=${TIMEZONE}
      restart: unless-stopped

volumes:
  caddy_data:
    external: true
  kimai_data:
    external: true
  mysql_data:
    external: true
